export const COUNTRY_CODES = [
  { code: "+1", label: "+1 US" },
  { code: "+81", label: "+81 JP" },
  { code: "+86", label: "+86 CN" },
  { code: "+886", label: "+886 TW" },
  { code: "+852", label: "+852 HK" },
  { code: "+65", label: "+65 SG" },
  { code: "+66", label: "+66 TH" },
  { code: "+84", label: "+84 VN" },
  { code: "+62", label: "+62 ID" },
  { code: "+60", label: "+60 MY" },
  { code: "+63", label: "+63 PH" },
  { code: "+91", label: "+91 IN" },
  { code: "+44", label: "+44 UK" },
  { code: "+49", label: "+49 DE" },
  { code: "+33", label: "+33 FR" },
  { code: "+61", label: "+61 AU" },
  { code: "+64", label: "+64 NZ" },
  { code: "+82", label: "+82 KR" },
  { code: "+7", label: "+7 RU" },
  { code: "+55", label: "+55 BR" },
  { code: "+52", label: "+52 MX" },
  { code: "+34", label: "+34 ES" },
  { code: "+39", label: "+39 IT" },
] as const;

export const NATIONALITIES = [
  { value: "US", label: "United States" },
  { value: "JP", label: "Japan" },
  { value: "CN", label: "China" },
  { value: "TW", label: "Taiwan" },
  { value: "HK", label: "Hong Kong" },
  { value: "SG", label: "Singapore" },
  { value: "TH", label: "Thailand" },
  { value: "VN", label: "Vietnam" },
  { value: "ID", label: "Indonesia" },
  { value: "MY", label: "Malaysia" },
  { value: "PH", label: "Philippines" },
  { value: "IN", label: "India" },
  { value: "GB", label: "United Kingdom" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "AU", label: "Australia" },
  { value: "NZ", label: "New Zealand" },
  { value: "KR", label: "South Korea" },
  { value: "RU", label: "Russia" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },
  { value: "ES", label: "Spain" },
  { value: "IT", label: "Italy" },
  { value: "CA", label: "Canada" },
] as const;
